name: Deno Deploy 2

on:
  workflow_dispatch:
  push:

env:
  APP_ID: ${{ secrets.APP_ID }}
  APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
  APP_INSTALLATION_ID: ${{ secrets.APP_INSTALLATION_ID }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    environment: ${{ (github.ref == 'refs/heads/main' || github.event.workflow_run.head_branch == 'main') && 'main' || 'development' }}
    permissions:
      contents: write
      id-token: write

    steps:
      - name: Set ACTION_REF environment variable
        run: |
          branch_name=$(echo '${{ github.event.workflow_run.head_branch || github.ref }}' | sed 's#refs/heads/##')
          echo "ACTION_REF=${GITHUB_REPOSITORY}@${branch_name}" >> $GITHUB_ENV

      - name: Prepare Environment Variables
        run: |
          branch_name=$(echo '${{ github.event.workflow_run.head_branch || github.ref }}' | sed 's#refs/heads/##' | sed 's#[^a-zA-Z0-9]#-#g')
          project_name="${{ github.event.repository.name }}"
          new_name="${project_name}-${branch_name}"
          # Deno project names cannot exceed 26 characters
          new_name=$(echo "$new_name" | cut -c 1-26)
          echo "PROJECT_NAME=$new_name" >> $GITHUB_ENV

      - uses: Meniole/deno-deploy@main
        env:
          KERNEL_PUBLIC_KEY: ${{ secrets.KERNEL_PUBLIC_KEY }}
          APP_ID: ${{ env.APP_ID }}
          APP_PRIVATE_KEY: ${{ env.APP_PRIVATE_KEY }}
          APP_INSTALLATION_ID: ${{ env.APP_INSTALLATION_ID }}
          ACTION_REF: ${{ env.ACTION_REF }}
        with:
          token: ${{ secrets.DENO_DEPLOY_TOKEN }}
