name: Deno Delete

on:
  delete:

env:
  APP_ID: ${{ secrets.APP_ID }}
  APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Delete Deno Project
    environment: ${{ github.event.ref == 'refs/heads/main' && 'main' || 'development' }}
    permissions:
      contents: write
      id-token: write

    steps:
      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Install CLI
        run: deno install -gArf jsr:@deno/deployctl

      - name: Prepare Environment Variables
        run: |
          branch_name=$(echo '${{ github.event.ref }}' | sed 's#refs/heads/##' | sed 's#[^a-zA-Z0-9]#-#g')
          project_name="${{ github.event.repository.name }}"
          new_name="${project_name}-${branch_name}"
          # Deno project names cannot exceed 26 characters
          new_name=$(echo "$new_name" | cut -c 1-26)
          echo "PROJECT_NAME=$new_name" >> $GITHUB_ENV

      - name: Manage Deno Deploy Project
        id: deno_project
        env:
          DENO_DEPLOY_TOKEN: ${{ secrets.DENO_DEPLOY_TOKEN }}
        run: |
          deployctl projects delete \
            --token=$DENO_DEPLOY_TOKEN \
            --project=$PROJECT_NAME \
            --force \
            --color=never || true

      - name: Write Deployment URL to Summary
        run: |
          echo "### Deployment URL" >> $GITHUB_STEP_SUMMARY
          echo 'Deployment `${{ env.PROJECT_NAME }}` has been deleted.' >> $GITHUB_STEP_SUMMARY
